name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install .
        python -m pip install coverage codecov
        python -m pip install pytest
    - name: Run coverage
      run: |
        coverage run -m pytest test/test.py
    - name: Run codecov
      if: success()
      env:
        CODECOV_TOKEN: "4e126a06-94fb-4a8c-aff4-3997f350e947"
      run: |
        codecov
